/*用户*/
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('USER','用户管理','ADD','新增用户信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('USER','用户管理','UPDATE','修改用户信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('USER','用户管理','DELETE','删除用户信息','01','西信基础平台');

/*角色*/
INSERT INTO TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) VALUES('ROLE','角色管理','ADD','新增角色信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('ROLE','角色管理','UPDATE','修改角色信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('ROLE','角色管理','DELETE','删除角色信息','01','西信基础平台');


