INSERT INTO TS_DICT_TYPE (TYPE_CODE,TYPE_NAME,TYPE_NAME_EN)values ('DATA_PERMISSION_TYPE','数据权限类型','Data Permission Type');
INSERT INTO TS_DICT_ENTRY(TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES ((SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='DATA_PERMISSION_TYPE'),'0_ALL','所有','ALL',1);
INSERT INTO TS_DICT_ENTRY(TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES ((SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='DATA_PERMISSION_TYPE'),'1_DEPT_AND_SUB','本部门及下属部门','Dept&Sub',2);
INSERT INTO TS_DICT_ENTRY(TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES ((SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='DATA_PERMISSION_TYPE'),'2_DEPT','本部门','Dept',3);
INSERT INTO TS_DICT_ENTRY(TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES ((SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='DATA_PERMISSION_TYPE'),'3_PERSONAL','本人','Personal',4);
INSERT INTO TS_DICT_ENTRY(TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES ((SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='DATA_PERMISSION_TYPE'),'99_SCRIPT','自定义','Customize',99);

INSERT INTO TS_DATA_PERMISSION_NEW(MENU_ID,DAO_INTERFACE) VALUES (9901,'com.wis.basis.systemadmin.dao.UserDao');



