INSERT INTO TS_DICT_TYPE(ID,TYPE_CODE,TYPE_NAME,TYPE_NAME_EN)  VALUES (SEQ_DICT_TYPE_ID.NEXTVAL,'LOGINSTATUS','登陆状态','Status');
INSERT INTO TS_DICT_TYPE(ID,TYPE_CODE,TYPE_NAME,TYPE_NAME_EN)  VALUES (SEQ_DICT_TYPE_ID.NEXTVAL,'GENDER','性别', 'Gender');
INSERT INTO TS_DICT_TYPE(ID,TYPE_CODE,TYPE_NAME,TYPE_NAME_EN)  VALUES (SEQ_DICT_TYPE_ID.NEXTVAL,'ORGNIZATION_DIMENSION','组织架构维度','Dimension');
--INSERT INTO TS_DICT_TYPE(TYPE_CODE,TYPE_NAME,TYPE_NAME_EN)  VALUES ('DATA_PERMISSION_VALUE_TYPE','数据权限值类型','Data Permission');
INSERT INTO TS_DICT_TYPE(ID,TYPE_CODE,TYPE_NAME,TYPE_NAME_EN)  VALUES (SEQ_DICT_TYPE_ID.NEXTVAL,'ORGNIZATION_TYPE','组织架构类型','Type');
INSERT INTO TS_DICT_TYPE(ID,TYPE_CODE,TYPE_NAME,TYPE_NAME_EN)  VALUES (SEQ_DICT_TYPE_ID.NEXTVAL,'ENABLE_STATUS','启用状态','Enabled');
INSERT INTO TS_DICT_TYPE(ID,TYPE_CODE,TYPE_NAME,TYPE_NAME_EN)  VALUES (SEQ_DICT_TYPE_ID.NEXTVAL,'YES_OR_NO','是/否','Y/N');

INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='LOGINSTATUS') ,'NORMAL','正常','Normal',1);
INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='LOGINSTATUS' ),'LOCK','锁定','Locked',2);

INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='GENDER') ,'M','男','Male',1);
INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='GENDER'),'F','女','Female',2);
INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='GENDER'),'U','未知','Unknow',3);

INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='ORGNIZATION_TYPE'),'COMPANY','公司','Company',1);
INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='ORGNIZATION_TYPE'),'PART','部门','Department',2);

insert into TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='ORGNIZATION_DIMENSION'),'ADMIN','行政维度','Admin',1);

INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='ENABLE_STATUS') ,'ENABLE','启用','Enable',1);
INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='ENABLE_STATUS' ),'DISABLE','禁用','Disable',2);

INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='YES_OR_NO'),'Y','是','Yes',1);
INSERT INTO TS_DICT_ENTRY(ID,TYPE_ID,ENTRY_CODE,ENTRY_NAME,ENTRY_NAME_EN,SORT_NO) VALUES (SEQ_DICT_ENTRY_ID.NEXTVAL,(SELECT ID FROM TS_DICT_TYPE WHERE TYPE_CODE='YES_OR_NO'),'N','否','No',2);

--系统管理
INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_SYSTEM_MANAGEMENT','系统管理','System Management',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS) VALUES (99, null, 'MENU_SYSTEM_MANAGEMENT', 'laptop');

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_USER_MANAGEMENT','用户管理','User Management',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9901, 99, 'MENU_USER_MANAGEMENT', 'user', '/user/listInput.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990101, 9901, 'UserView', '用户查看',1);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990102, 9901, 'UserEdit', '用户编辑',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_ROLE_MANAGEMENT','角色管理','Role Management',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9902, 99, 'MENU_ROLE_MANAGEMENT', 'cog', '/role/listInput.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990201, 9902, 'RoleView', '角色查看',1);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990202, 9902, 'RoleEdit', '角色编辑',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_DICTIONARY_TYPE_MANAGEMENT','字典类型管理','Dictionary Type',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9903, 99, 'MENU_DICTIONARY_TYPE_MANAGEMENT', 'book', '/type/listInput.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990301, 9903, 'TypeView', '字典类型查看',1);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990302, 9903, 'TypeEdit', '字典类型编辑',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_DICTIONARY_PARAMETER_MANAGEMENT','字典参数管理','Dictionary Parameter',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9904, 99, 'MENU_DICTIONARY_PARAMETER_MANAGEMENT', 'archive', '/entry/listInput.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990401, 9904, 'EntryView', '字典参数查看',1);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990402, 9904, 'EntryEdit', '字典参数编辑',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_ORGNIZATION_MANAGEMENT','组织架构管理','Orgnization Management',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9905, 99, 'MENU_ORGNIZATION_MANAGEMENT', 'sitemap', '/orgnization/listTreeInput.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990501, 9905, 'OrgnizationView', '组织架构查看',1);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990502, 9905, 'OrgnizationEdit', '组织架构编辑',0);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990503, 9905, 'OrgnizationAdd', '组织架构新增',0);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990504, 9905, 'OrgnizationDelete', '组织架构删除',0);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990505, 9905, 'PositionAdd', '岗位新增',0);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990506, 9905, 'PositionEdit', '岗位编辑',0);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990507, 9905, 'PositionDelete', '岗位删除',0);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990508, 9905, 'UserOrgEdit', '人员编辑',0);

--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_FORM_PERMISSION_MANAGEMENT','表单权限管理','FormPermission Management',0);
--INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9906, 99, 'MENU_FORM_PERMISSION_MANAGEMENT', 'list', '/formPermission/listInput.do' );
--INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990601, 9906, 'FormPermissionView', '表单权限查看',1);
--INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990602, 9906, 'FormPermissionEdit',   '表单权限编辑',0);
--
--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_DATA_PERMISSION_MANAGEMENT','数据权限管理','DataPermission Management',0);
--INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9907, 99, 'MENU_DATA_PERMISSION_MANAGEMENT', 'th', '/dataPermission/listInput.do' );
--INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990701, 9907, 'DataPermissionView', '数据权限查看',1);
--INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990702, 9907, 'DataPermissionEdit',   '数据权限编辑',0);
--
--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_FORM_PERMISSION_SET_MANAGEMENT','表单权限集管理','FormPermissionSet Management',0);
--INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9908, 99, 'MENU_FORM_PERMISSION_SET_MANAGEMENT', 'list-alt', '/formPermissionSet/listInput.do' );
--INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990801, 9908, 'FormPermissionSetView', '表单权限集查看',1);
--INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990802, 9908, 'FormPermissionSetEdit',   '表单权限集编辑',0);
--
--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_DATA_PERMISSION_SET_MANAGEMENT','数据权限集管理','DataPermissionSet Management',0);
--INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9909, 99, 'MENU_DATA_PERMISSION_SET_MANAGEMENT', 'th-list', '/dataPermissionSet/listInput.do' );
--INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990901, 9909, 'DataPermissionSetView', '数据权限集查看',1);
--INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (990902, 9909, 'DataPermissionSetEdit',   '数据权限集编辑',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_SYSTEM_CONFIG_MANAGEMENT','系统配置管理','SystemConfig Management',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9910, 99, 'MENU_SYSTEM_CONFIG_MANAGEMENT', 'foursquare', '/basis/configuration/listInput.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (991001, 9910, 'SystemConfigView', '系统配置查看',1);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (991002, 9910, 'SystemConfigEdit',   '系统配置编辑',0);

INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'PWD_REG_EXP','密码验证规则' ,'*6-18','*','设置验证密码长度');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'PWD_DUPLICATION_VERIFY','启用密码重复校验' ,'true','*','设置是否启用密码重复校验');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'DEL_PVP_COUNT','密码不重复次数' ,'3','n1-3','设置修改密码不能与前几次设置的密码重复');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'PWD_VALIDITY_PERIOD_VERIFY','启用密码有效期校验' ,'true','*','设置是否启用密码有效期校验');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'PWD_VALIDITY_PERIOD','密码有效期(天)' ,'90','n1-3','设置用户密码有效期');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'PWD_RESET_DEFAULT','重置默认密码' ,'aaaa1111','*','重置密码使用此密码');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'SMTP_HOST','SMTP服务器' ,'smtp.exmail.qq.com','*','设置SMTP主机地址');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'SMTP_USER_NAME','邮件账户' ,'isbg_support@westinfosoft.com','e','设置系统发件人账户');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'SMTP_PASSWORD','邮件账户密码' ,'isbg0822','*','设置系统发件人密码');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'IMG_BASE_URL','图片资源根地址' ,'http://localhost:8080/static/images/','url','设置图片文件的根url');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'ATTACHMENT_BASE_PATH','附件资源根目录' ,'D:\app\static\attachments\','*','设置文件资源存放的根目录');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'IMG_BASE_PATH','图片资源根目录' ,'D:\app\static\images\','*','设置图片资源存放的根目录');
INSERT INTO TS_GLOBAL_CONFIGURATION(ID,SYS_KEY,NAME,SYS_VALUE,PROPERTY,REMARK) VALUES(SEQ_GLOBAL_CONFIGURATION_ID.NEXTVAL,'BPM_SEND_TASK_TODO_MAIL','任务创建时是否发送提醒邮件' ,'true','*','设置任务创建时是否发送提醒邮件');

--系统监控
INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_SYSTEM_MONITORING','系统监控','System Monitoring',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS) VALUES (98, null, 'MENU_SYSTEM_MONITORING', 'eye-open');

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_AUDIT_LOG','审计日志','Audit Log',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9801, 98, 'MENU_AUDIT_LOG', 'file-text-alt', '/audit/listInput.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (980101, 9801, 'AuditLogView', '审计日志查看',1);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (980102, 9801, 'AuditLogEdit',   '审计日志编辑',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_JOB','定时任务','Job Definiition',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9802, 98, 'MENU_JOB', 'spinner', '/job/listInput.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (980201, 9802, 'JobView', '定时任务查看',1);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (980202, 9802, 'JobEdit', '定时任务编辑',0);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (980204, 9802, 'JobPause', '定时任务暂停',0);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (980205, 9802, 'JobResume', '定时任务恢复',0);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (980206, 9802, 'JobRunImmediately', '定时任务立即执行',0);
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (980207, 9802, 'JobLogView', '定时任务日志查看',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_DATA_MONITORING','数据监控','Data Monitoring',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9803, 98, 'MENU_DATA_MONITORING', 'tasks', '/dataSource/druid.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (980301, 9803, 'DataMonitorView', '数据监控查看',1);

INSERT INTO TS_LANGUAGE(CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES ('MENU_SYSTEM_MONITORING','系统监控','System Monitoring',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9804, 98, 'MENU_SYSTEM_MONITORING', 'laptop', '/system/monitor.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (980401, 9804, 'SystemMonitorView', '系统监控查看',1);

--消息中心
--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_MESSAGE_CENTER','消息中心','Message Center',0);
--insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS) VALUES (97, null, 'MENU_MESSAGE_CENTER', 'comments');
--
--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_NOTIFICATION','通知','Notification',0);
--INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9701, 97, 'MENU_NOTIFICATION', 'bell', '/notification/myListInput.do' );
--insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (970101, 9701, 'MyNotificationListView', '通知列表查看', 1);
--
--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_NOTIFICATION_MANAGEMENT','通知管理','Notification Management',0);
--INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9702, 97, 'MENU_NOTIFICATION_MANAGEMENT', 'comment', '/notification/managementListInput.do' );
--insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (970201, 9702, 'NotificationManagementListView', '通知列表查看', 1);
--insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (970202, 9702, 'NotificationManagementListEdit', '通知列表编辑', 0);
--
--开发视图
--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_DEV_CENTER','开发中心','Develop Center',0);
--insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS) VALUES (00, null, 'MENU_DEV_CENTER', 'gear');
--
--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_GENERATE_CODE','代码生成','Generate Code',0);
--INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (0001, 00, 'MENU_GENERATE_CODE', 'code', '/codeGen/mainInput.do' );
--insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (000101, 0001, 'GenerateCodeMainView', '代码生成查看', 1);

--流程平台
INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PROCESS_MANAGER','流程管理','Process Manager',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS) VALUES (96, null, 'MENU_PROCESS_MANAGER', 'bar-chart');

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PROCESS_MODEL','模型定义管理','Model Design',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9601, 96, 'MENU_PROCESS_MODEL', 'lemon', '/bpm/model/manage/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960101, 9601, 'ModelDesignView', '模型定义查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960102, 9601, 'ModelAdd', '模型新增',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960103, 9601, 'ModelUpdate', '模型编辑',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960104, 9601, 'ModelDeploy', '部署',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960105, 9601, 'ModelDelete', '模型删除',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960106, 9601, 'ModelExport', '模型导出',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PROCESS_LIST','流程定义管理','Process List',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9602, 96, 'MENU_PROCESS_LIST', 'search', '/bpm/definition/manage/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960201, 9602, 'ProcessListView', '流程列表查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960202, 9602, 'ProcessHangup', '挂起',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960203, 9602, 'ProcessActive', '激活',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960204, 9602, 'ProcessDelete', '删除',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960205, 9602, 'ProcessConvert', '转换为MODEL',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960206, 9602, 'ProcessConfig', '流程配置',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960208, 9602, 'ProcessDeploy', '流程部署',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PROCESS_RUNNING','运行流程管理','Process Running',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9603, 96, 'MENU_PROCESS_RUNNING', 'building', '/bpm/instance/manage/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960301, 9603, 'ProcessRunningView', '流程运行中查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960302, 9603, 'ProcessRunningHangup', '挂起',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960303, 9603, 'ProcessRunningActive', '激活',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960304, 9603, 'ProcessRunningDelete', '删除',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960305, 9603, 'ProcessRunningPicture', '历史图表',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PUNNING_TASK','运行任务管理','Runnig Task',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9604, 96, 'MENU_PUNNING_TASK', 'folder-close-alt', '/bpm/task/todo/manage/listInput.do');
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960401, 9604, 'RunningTaskView', '运行任务查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960402, 9604, 'RunningTaskDelegate', '转办',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960403, 9604, 'RunningTaskPicture', '历史图表',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960404, 9604, 'RunningTaskJump', '自由跳转',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PROCESS_ENDED','历史流程管理','Process Ended',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9605, 96, 'MENU_PROCESS_ENDED', 'camera', '/bpm/hisinstance/manage/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960501, 9605, 'ProcessEndView', '流程完结的查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960502, 9605, 'ProcessEndPicture', '历史图表',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PROCESS_DELEGATE_MANAGEMENT','委托管理','Delegate Management',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9606, 96, 'MENU_PROCESS_DELEGATE_MANAGEMENT', 'credit-card', '/bpm/manage/delegateconfig/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960601, 9606, 'DelegateManamentView', '流程代理查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960602, 9606, 'DelegateManamentAdd', '新增',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960603, 9606, 'DelegateManamentUpdate', '编辑',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960604, 9606, 'DelegateManamentDelete', '删除',0);

--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_TASK_REMIND','任务处理提醒管理','Task Remind',0);
--insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9607, 96, 'MENU_TASK_REMIND', 'time', '/bpm/manage/remind/listInput.do');
--insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960701, 9607, 'TaskRemindView', '任务处理提醒查看',1);
--insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960702, 9607, 'TaskRemindEdit', '任务处理提醒编辑',0);
--insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (960703, 9607, 'TaskRemindRelease', '任务处理提醒发布',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PROCESS_MYPROCESS','我的流程','MyProcess',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS) VALUES (95, null, 'MENU_PROCESS_MYPROCESS', 'folder-close');

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_LAUNCH_NEWPROCESS','发起新的流程','Launch NewProcess',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9501, 95, 'MENU_LAUNCH_NEWPROCESS', 'star', '/bpm/definition/personal/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950101, 9501, 'LaunchNewProcessView', '发起新流程查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950102, 9501, 'LaunchNewProcessStart', '启动',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_RUNNING_PROCESS','运行的流程','Running Process',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9502, 95, 'MENU_RUNNING_PROCESS', 'bullseye', '/bpm/instance/personal/running/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950201, 9502, 'RunningProcessView', '运行中流程查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950202, 9502, 'RunningProcessStop', '终止',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950203, 9502, 'RunningProcessPicture', '历史图表',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_END_PROCESS','完结的流程','End Process',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9503, 95, 'MENU_END_PROCESS', 'ticket', '/bpm/hisinstance/personal/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950301, 9503, 'EndProcessView', '完结流程查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950302, 9503, 'EndProcessPicture', '历史图表',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PARTAKE_PROCESS','参与的流程','Partake Process',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9504, 95, 'MENU_PARTAKE_PROCESS', 'leaf', '/bpm/instance/personal/involved/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950401, 9504, 'PartakeProcessView', '参与的流程查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950402, 9504, 'PartakeProcessPicture', '历史图表',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PROCESS_DELEGATE_CONFIG','委托设置','Delegate Config',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9505, 95, 'MENU_PROCESS_DELEGATE_CONFIG', 'file-text-alt', '/bpm/myoffice/delegateconfig/listInput.do');
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950501, 9505, 'DelegateConfigView', '委托设置查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950502, 9505, 'DelegateConfigAdd', '新增',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950503, 9505, 'DelegateConfigUpdate', '编辑',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (950504, 9505, 'DelegateConfigDelete', '删除',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PROCESS_MYTASK','我的任务','MyTask',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS) VALUES (94, null, 'MENU_PROCESS_MYTASK', 'folder-open');

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_TODO_TASK','待办任务','Todo Task',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9401, 94, 'MENU_TODO_TASK', 'folder-open-alt', '/bpm/task/todo/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (940101, 9401, 'TodoTaskView', '待办任务查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (940102, 9401, 'TodoTaskDo', '办理',0);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_DONE_TASK','已办任务','Done Task',0);
insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9402, 94, 'MENU_DONE_TASK', 'wrench', '/bpm/task/completed/listInput.do' );
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (940201, 9402, 'DoneTaskView', '已办任务查看',1);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (940202, 9402, 'DoneTaskPicture', '历史图表',0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (940203, 9402, 'DoneTaskRecall', '召回',0);

--INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL,'MENU_PROXY_TASK','代理中的任务','Proxy Task',0);
--insert into TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (9403, 94, 'MENU_PROXY_TASK', 'money', '/bpm/task/delegating/listInput.do');
--insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (940301, 9403, 'ProxyTaskView', '代理中任务查看',1);
--insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (940302, 9403, 'ProxyTaskEdit', '代理中任务操作',0);

INSERT INTO TS_ROLE (ID, ROLE_CODE, ROLE_NAME, ROLE_DESC,  OPT_COUNTER, MARK_FOR_DELETE) VALUES (1, 'admin', '系统管理员', '系统管理员', '1','0');
INSERT INTO TS_USER (ID, ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES (1,  'admin', 'c3ce8345d3599ab8a4c337d9fb0d0d93', 'NORMAL',0,'张琦','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) SELECT 1, ID FROM TS_PERMISSION;
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (1, 1);