/*用户*/
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('USER','用户管理','ADD','新增用户信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('USER','用户管理','UPDATE','修改用户信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('USER','用户管理','DELETE','删除用户信息','01','西信基础平台');

/*角色*/
INSERT INTO TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) VALUES('ROLE','角色管理','ADD','新增角色信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('ROLE','角色管理','UPDATE','修改角色信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('ROLE','角色管理','DELETE','删除角色信息','01','西信基础平台');

/*不合格组*/
INSERT INTO TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) VALUES('NC_GROUP','不合格组管理','ADD','新增不合格组信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('NC_GROUP','不合格组管理','UPDATE','修改不合格组信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('NC_GROUP','不合格组管理','DELETE','删除不合格组信息','01','西信基础平台');

/*不合格代码*/
INSERT INTO TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) VALUES('NC','不合格代码管理','ADD','新增不合格代码信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('NC','不合格代码管理','UPDATE','修改不合格代码信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('NC','不合格代码管理','DELETE','删除不合格代码信息','01','西信基础平台');

/*报废代码*/
INSERT INTO TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) VALUES('SCRAP','报废代码管理','ADD','新增报废代码信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('SCRAP','报废代码管理','UPDATE','修改报废代码信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('SCRAP','报废代码管理','DELETE','删除报废代码信息','01','西信基础平台');

/*物料*/
INSERT INTO TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) VALUES('PART','物料管理','ADD','新增物料信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('PART','物料管理','UPDATE','修改物料信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('PART','物料管理','DELETE','删除物料信息','01','西信基础平台');

/*工艺路径*/
INSERT INTO TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) VALUES('PATH','工艺路径管理','ADD','新增工艺路径信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('PATH','工艺路径管理','UPDATE','修改工艺路径信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('PATH','工艺路径管理','DELETE','删除工艺路径信息','01','西信基础平台');

/*工艺路径站点*/
INSERT INTO TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) VALUES('PATH_ULOC','工艺路径站点管理','ADD','新增工艺路径站点信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('PATH_ULOC','工艺路径站点管理','UPDATE','修改工艺路径站点信息','01','西信基础平台');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('PATH_ULOC','工艺路径站点管理','DELETE','删除工艺路径站点信息','01','西信基础平台');

/*BOM管理*/
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) VALUES('TmBom','BOM管理','ADD','新增BOM信息','01','MES制造管理系统');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('TmBom','BOM管理','UPDATE','修改BOM信息','01','MES制造管理系统');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('TmBom','BOM管理','DELETE','删除BOM信息','01','MES制造管理系统');

insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) VALUES('TmBomDetail','BOM明细管理','ADD','新增BOM明细信息','01','MES制造管理系统');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('TmBomDetail','BOM明细管理','UPDATE','修改BOM明细信息','01','MES制造管理系统');
insert into TS_AUDIT_CONFIG(AUDIT_TYPE_ID,AUDIT_TYPE_NAME,OPERATE_TYPE_ID,OPERATE_TYPE_NAME,AUDIT_SYSTEM_ID,AUDIT_SYSTEM_NAME) values('TmBomDetail','BOM明细管理','DELETE','删除BOM明细信息','01','MES制造管理系统');
