--系统管理
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_NAME','用户名称',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_ACCOUNT_NUMBER','帐号',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_STATUS','用户状态',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_SEX','性别',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_MAIL','邮箱',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_PHONE','电话',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_FAX','传真',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_TYPE','用户类型',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('LAST_LOGIN_DATE','最后登录日期',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_ADDRESS','地址',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('REAL_NAME','真实姓名',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PASSWORD','密码',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('VERIFY_PASSWORD','重复密码',9901,'USER');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('POSITION','岗位设置',9901,'USER');

INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ROLE_CODE','角色代码',9902,'ROLE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ROLE_NAME','角色名称',9902,'ROLE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ROLE_DESC','角色描述',9902,'ROLE');

INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('TYPE_CODE','类型代码',9903,'DICT_TYPE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('TYPE_NAME','类型名称',9903,'DICT_TYPE');

INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('TYPE_CODE','类型代码',9904,'DICT_ENTRY');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('TYPE_NAME','类型名称',9904,'DICT_ENTRY');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ENTRY_CODE','参数代码',9904,'DICT_ENTRY');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ENTRY_NAME','参数名称',9904,'DICT_ENTRY');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ENTRY_SORT','顺序',9904,'DICT_ENTRY');

INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ORG_NAME','组织架构名称',9905,'ORGNIZATION');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ORG_CODE','组织架构代码',9905,'ORGNIZATION');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ORG_TYPE','组织架构类型',9905,'ORGNIZATION');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ORG_PARENT_NAME','上级组织',9905,'ORGNIZATION');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ORG_MENU_ID','组织架构描述',9905,'ORGNIZATION');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('DIMENSION_NAME','维度名称',9905,'ORGNIZATION');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ORG_LEADER','组织负责人',9905,'ORGNIZATION');

INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('POSITION_PARENT','上级岗位',9905,'POSITION');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('POSITION_CODE','岗位代码',9905,'POSITION');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('POSITION_NAME','岗位名称',9905,'POSITION');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('POSITION_DESCRIPTION','岗位描述',9905,'POSITION');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ORG_NAME','组织名称',9905,'POSITION');

INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('OPERATE_DATE','操作时间',9911,'AUDIT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('AUDIT_TYPE_NAME','操作对象',9911,'AUDIT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('OPERATION_NAME','操作类型',9911,'AUDIT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('AUDIT_SYSTEM_NAME','操作系统',9911,'AUDIT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('BEFORE_OPERATE_OBJ','操作前信息',9911,'AUDIT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('AFTER_OPERATE_OBJ','操作后信息',9911,'AUDIT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('OPERATE_END_TIME','结束时间',9911,'AUDIT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('OPERATE_START_TIME','开始时间',9911,'AUDIT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('OPERATOR_NAME','用户名称',9911,'AUDIT');

--
--/*===流程管理->模型定义===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('MODEL_COL_KEY','key',9601,'MODEL_DEFINITION_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('MODEL_COL_NAME','名称',9601,'MODEL_DEFINITION_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_SERVISION','版本号',9601,'MODEL_DEFINITION_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('MODEL_COL_CREATETIME','创建时间',9601,'MODEL_DEFINITION_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('MODEL_COL_UPDATETIME','最新修改时间',9601,'MODEL_DEFINITION_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('MODEL_COL_DESCRIPTION','描述',9601,'MODEL_DEFINITION_LIST');

/*==流程管理->流程列表===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_TITLE','标题',9602,'PROCESS_MANAGER_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_STATUS','状态',9602,'PROCESS_MANAGER_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_DESC','描述',9602,'PROCESS_MANAGER_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_IMG','图片',9602,'PROCESS_MANAGER_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_XML','XML',9602,'PROCESS_MANAGER_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_SERVISION','版本号',9602,'PROCESS_MANAGER_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('RPOCESS_COLUMN_CREATTIME','创建时间',9602,'PROCESS_MANAGER_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_CREATUSER','创建人',9602,'PROCESS_MANAGER_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_DEF_ID','流程定义ID',9602,'PROCESS_MANAGER_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_HISTORY_URL','流程历史URL',9602,'PROCESS_MANAGER_LIST');

/*==流程管理->运行流程管理===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_ID','实例ID',9603,'RUNNING_INSTANCE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_PROCESS','流程名称',9603,'RUNNING_INSTANCE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_STATE','状态',9603,'RUNNING_INSTANCE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_ACT_NAME','当前节点',9603,'RUNNING_INSTANCE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_CREATEUSER','发起人',9603,'RUNNING_INSTANCE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_CREATE_TIME','发起时间',9603,'RUNNING_INSTANCE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_OWNER','负责人',9603,'RUNNING_INSTANCE');

/*===流程管理->运行任务管理===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('NAME','名称',9604,'RUNNIG_TASK_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_NAME','流程名称',9604,'RUNNIG_TASK_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('CREATE_TIME','创建时间',9604,'RUNNIG_TASK_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ASSIGNEE','负责人帐号',9604,'RUNNIG_TASK_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('INITIATOR','流程发起人',9604,'RUNNIG_TASK_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_ACCOUNT','代理人帐号',9604,'RUNNIG_TASK_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('USER_NAME','代理人名称',9604,'RUNNIG_TASK_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('DESCRIPTION','描述',9604,'RUNNIG_TASK_MANAGEMENT');

/*===流程管理->历史流程管理===*/
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_PROCESSDEFINITIONID','流程定义ID',9605,'PROCESS_HISTORY_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_NAME','名称',9605,'PROCESS_HISTORY_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_STARTUSERID','流程发起人',9605,'PROCESS_HISTORY_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_STARTTIME','流程开始时间',9605,'PROCESS_HISTORY_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_ENDTIME','流程结束时间',9605,'PROCESS_HISTORY_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_DESC','备注',9605,'PROCESS_HISTORY_LIST');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_USER','负责人',9605,'PROCESS_HISTORY_LIST');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_RESULT','处理结果',9605,'PROCESS_HISTORY_LIST');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_VALUE','值',9605,'PROCESS_HISTORY_LIST');

/*===流程管理->委托管理===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('CURRENT_USER','委托人',9606,'DELEGATE_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('TARGET_USER','被委托人',9606,'DELEGATE_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('START_TIME','开始时间',9606,'DELEGATE_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('END_TIME','结束时间',9606,'DELEGATE_MANAGEMENT');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_DEFINITION_NAME','流程名称',9606,'DELEGATE_MANAGEMENT');

/*===流程管理->任务处理提醒===*/
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_NAME','流程名称',9607,'TASK_REMIND_MANAGEMENT');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_MENU_ID','流程描述',9607,'TASK_REMIND_MANAGEMENT');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_VERSION','流程版本',9607,'TASK_REMIND_MANAGEMENT');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('NODE_NAME','节点名称',9607,'TASK_REMIND_MANAGEMENT');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('NODE_MENU_ID','节点描述',9607,'TASK_REMIND_MANAGEMENT');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('TITLE','标题',9607,'TASK_REMIND_MANAGEMENT');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('REMINDER_NAME','提醒人名称',9607,'TASK_REMIND_MANAGEMENT');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('REMINDER_ACCOUNT','提醒人账号',9607,'TASK_REMIND_MANAGEMENT');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('EXPRESSION','提醒时间',9607,'TASK_REMIND_MANAGEMENT');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('RELEASED','是否发布',9607,'TASK_REMIND_MANAGEMENT');

--/*===我的任务===*/
-- /*===我的任务->待办任务===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('NAME','名称',9401,'TASK_TODO');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_NAME','流程名称',9401,'TASK_TODO');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('OWNER','负责人',9401,'TASK_TODO');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('TASK_ID','任务ID',9401,'TASK_TODO');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_ID','流程实例ID',9401,'TASK_TODO');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('CREATE_TIME','创建时间',9401,'TASK_TODO');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('START_USER_NAME','发起人',9401,'TASK_TODO');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('DESCRIPTION','描述',9401,'TASK_TODO');
--
--/*===我的任务->已办任务===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('NAME','任务名称',9402,'TASK_COMPLETED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_NAME','流程名称',9402,'TASK_COMPLETED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('TASK_ID','任务ID',9402,'TASK_COMPLETED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_ID','流程实例ID',9402,'TASK_COMPLETED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('END_TIME','结束时间',9402,'TASK_COMPLETED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('OWNER','负责人',9401,'TASK_COMPLETED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('START_USER_NAME','发起人',9402,'TASK_COMPLETED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('DESCRIPTION','描述',9402,'TASK_COMPLETED');
--
--/*===我的任务->代理中的任务===*/
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('TASK_ID','任务ID',9403,'TASK_DELEGATING');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('NAME','流程节点名称',9403,'TASK_DELEGATING');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_ID','流程实例ID',9403,'TASK_DELEGATING');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_NAME','流程名称',9403,'TASK_DELEGATING');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('CREATE_TIME','创建时间',9403,'TASK_DELEGATING');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('ASSIGNEE_NAME','负责人',9403,'TASK_DELEGATING');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('DESCRIPTION','描述',9403,'TASK_DELEGATING');

--/*===我的流程===*/
--/*===我的流程 -》发起新的流程===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_TITLE','标题',9501,'PROCESS_START_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_NAME','标题',9501,'PROCESS_START_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_STATUS','流程状态',9501,'PROCESS_START_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_DESC','描述',9501,'PROCESS_START_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_IMG','图片',9501,'PROCESS_START_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_SERVISION','版本号',9501,'PROCESS_START_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('RPOCESS_COLUMN_CREATTIME','创建时间',9501,'PROCESS_START_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_CREATUSER','创建人',9501,'PROCESS_START_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_DEF_ID','流程定义ID',9501,'PROCESS_START_LIST');


--/*===我的流程 -》运行的流程===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_ID','实例ID',9502,'MY_INSTANCE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_PROCESS','流程名称',9502,'MY_INSTANCE');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_DEF_ID','流程定义ID',9502,'MY_INSTANCE');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_STATE_','流程状态',9502,'MY_INSTANCE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_ACT_NAME','当前节点',9603,'MY_INSTANCE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_CREATE_TIME','发起时间',9502,'MY_INSTANCE');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_CREATEUSER','发起人',9502,'MY_INSTANCE');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('BPM_TASK_COL_DESCRIPTION','任务描述',9502,'MY_INSTANCE');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_OWNER','负责人',9603,'MY_INSTANCE');


--/*===我的流程 -》完结的流程===*/
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_PROCESSDEFINITIONID','流程定义ID',9503,'PROCESS_COMPELETED_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_STARTTIME','流程开始时间',9503,'PROCESS_COMPELETED_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_ENDTIME','流程结束时间',9503,'PROCESS_COMPELETED_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_INSTANCE_NAME','流程名称',9503,'PROCESS_COMPELETED_LIST');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_DESC','描述',9503,'PROCESS_COMPELETED_LIST');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_ID','实例ID',9503,'PROCESS_COMPELETED_LIST');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_PROCESSDEFINITIONID_','流程ID',9503,'PROCESS_COMPELETED_LIST');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_STARTTIME_','创建时间',9503,'PROCESS_COMPELETED_LIST');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_ENDTIME_','结束时间',9503,'PROCESS_COMPELETED_LIST');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_STARTUSERID','负责人',9503,'PROCESS_COMPELETED_LIST');
--INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('HISTORIC_PROCESS_STARTUSERID_ACCOUNT','负责人帐号',9503,'PROCESS_COMPELETED_LIST');

--/*===我的流程 -》参与的流程===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_PROCESS','流程名称',9504,'INVOLVED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_ID','实例ID',9504,'INVOLVED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_COLUMN_DEF_ID','流程ID',9504,'INVOLVED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('BPM_TASK_COL_DESCRIPTION','描述',9504,'INVOLVED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('START_TIME_','开始时间',9504,'INVOLVED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('END_TIME_','结束时间',9504,'INVOLVED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_OWNER','负责人',9504,'INVOLVED');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_INSTANCE_DELETEREASON','处理结果',9504,'INVOLVED');

--/*===我的流程 -》委托设置===*/
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('TARGET_USER','被委托人',9505,'DELEGATE_CONFIG');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('START_TIME','开始时间',9505,'DELEGATE_CONFIG');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('END_TIME','结束时间',9505,'DELEGATE_CONFIG');
INSERT INTO TS_FORM_PERMISSION_NEW(PERMISSION_CODE,PERMISSION_NAME,MENU_ID,MODULE) VALUES ('PROCESS_DEFINITION_NAME','流程名称',9505,'DELEGATE_CONFIG');


INSERT INTO TR_ROLE_FROM_PERMISSION_NEW(ROLE_ID,PERMISSION_ID) SELECT 1,ID FROM TS_FORM_PERMISSION_NEW;

