--钣金原材料主数据
create table TM_SHEET_METAL_MATERIAL (
   ID                   NUMBER(10) PRIMARY KEY not null,
   MODEL_TYPE           VARCHAR2(64),
   PLACE_TYPE      		VARCHAR2(64),
   MATERIAL_DRAWING_NO  VARCHAR2(128),
   ASSEMBLY_LINE     	VARCHAR2(64),
   ML_LEVEL     		VARCHAR2(32),
   COATING_WITH     	VARCHAR2(64),
   CW_LEVEL			    VARCHAR2(32),
   MACHINING_SURFACE    VARCHAR2(64),
   MS_LEVEL     		VARCHAR2(32),
   PROGRAM_NUMBER      	VARCHAR2(128),
   PROGRESSION     		VARCHAR2(2),
   COMPONENT     		VARCHAR2(32),
   AFTER_PROCESS     	VARCHAR2(32),
   TEXTURE     			VARCHAR2(32),
   PLATE_THICKNESS     	VARCHAR2(16),
   MATERIAL_SIZE     	VARCHAR2(32),
   BATCH_NUMBER     	NUMBER(4),
   BATCH_CAP     		NUMBER(5),
   STEP_NUMBER     		NUMBER(3),
   MACHINE_TAGS     	VARCHAR2(128),
   MANUFACTURERS     	VARCHAR2(128),
   IDENTIFICATION_CODE  VARCHAR2(32),
   TOOL_NUMBER     		VARCHAR2(256),
   RES_TOOL_NUMBER   	VARCHAR2(256),
   REMARK     			VARCHAR2(512),
   CREATE_USER          NUMBER(10),
   UPDATE_USER          NUMBER(10),
   CREATE_TIME          TIMESTAMP,
   UPDATE_TIME          TIMESTAMP,
   MARK_FOR_DELETE 		CHAR(1) default '0' not null,
   OPT_COUNTER     		NUMBER(5) default 0 not null
);

--钣金设备保养主数据
create table TM_DEVICE_MAINTENANCE (
   ID                   NUMBER(10) PRIMARY KEY not null,
   DEVICE_CODE          VARCHAR2(64),
   DEVICE_NAME          VARCHAR2(128),
   MAINTENANCE_PROJECT  VARCHAR2(256),
   MAINTENANCE_UNIT  	VARCHAR2(32),
   MAINTENANCE_VALUE    NUMBER(10),
   REMARK     			VARCHAR2(512),
   CREATE_USER          NUMBER(10),
   UPDATE_USER          NUMBER(10),
   CREATE_TIME          TIMESTAMP,
   UPDATE_TIME          TIMESTAMP,
   MARK_FOR_DELETE 		CHAR(1) default '0' not null,
   OPT_COUNTER     		NUMBER(5) default 0 not null
);

--生产管理，源列表信息
create table TB_MP_SOURCE_DATA (
   ID                   NUMBER(10) PRIMARY KEY not null,
   TASK_DATE           	VARCHAR2(64),
   WORK_SCHEDULE      	VARCHAR2(64),
   MODEL  				VARCHAR2(128),
   APC_TOTAL_NUMBER     NUMBER(10),
   INVENTORY_NUMBER     NUMBER(10),
   PLANNED_PRODUCTION	NUMBER(10),
   SEND_PERIOD_TIME		VARCHAR2(128),
   DATA_TYPE			VARCHAR2(32),
   CREATE_USER          NUMBER(10),
   UPDATE_USER          NUMBER(10),
   CREATE_TIME          TIMESTAMP,
   UPDATE_TIME          TIMESTAMP,
   MARK_FOR_DELETE 		CHAR(1) default '0' not null,
   OPT_COUNTER     		NUMBER(5) default 0 not null
);

--生产管理，排产列表信息
create table TB_MP_SCHEDUL (
   ID                   NUMBER(10) PRIMARY KEY not null,
   SOURCE_DATA_ID		NUMBER(10),
   SCHEDUL_DATE         VARCHAR2(64),
   WORK_SCHEDULE      	VARCHAR2(64),
   MODEL  				VARCHAR2(128),
   BATCH_NUMBER			NUMBER(10),
   PRESS				VARCHAR2(256),
   MOULDS				VARCHAR2(256),
   DISPATCH_NUMBER		NUMBER(10),
   FINISH_NUMBER		NUMBER(10),
   SEND_WORKERS			VARCHAR2(128),
   STATUS      			VARCHAR2(32),
   DISPATCH_TIME		VARCHAR2(32),
   CREATE_USER          NUMBER(10),
   UPDATE_USER          NUMBER(10),
   CREATE_TIME          TIMESTAMP,
   UPDATE_TIME          TIMESTAMP,
   MARK_FOR_DELETE 		CHAR(1) default '0' not null,
   OPT_COUNTER     		NUMBER(5) default 0 not null
);

--生产管理，生产记录信息
create table TB_MP_PRODUCTION_RECORD (
   ID                   NUMBER(10) PRIMARY KEY not null,
   SCHEDUL_ID			NUMBER(10),
   PRODUCTION_DATE      VARCHAR2(64),
   MODEL          		VARCHAR2(128),
   BATCH_NUMBER     	NUMBER(10),
   WORK_PEOPLE        	VARCHAR2(512),
   WORK_SCHEDULE        VARCHAR2(64),
   PRESS        		VARCHAR2(256),
   MOULDS       		VARCHAR2(256),
   PLANNED_CYCLES   	NUMBER(10),
   PRACTICAL_CYCLES   	NUMBER(10),
   DEFECTIVE_NUMBER   	NUMBER(10),
   INVENTORY_CONSUMPTION   NUMBER(10),
   PRODUCTION_TIME    	VARCHAR2(64),   
   PERIOD_TAKE_TIME   	VARCHAR2(64),
   PLACE_TIME     		VARCHAR2(64),
   ALARM_NUMBER     	NUMBER(10),
   START_TIME     		VARCHAR2(64),
   END_TIME       		VARCHAR2(64),
   CREATE_USER          NUMBER(10),
   UPDATE_USER          NUMBER(10),
   CREATE_TIME          TIMESTAMP,
   UPDATE_TIME          TIMESTAMP,
   MARK_FOR_DELETE    	CHAR(1) default '0' not null,
   OPT_COUNTER        	NUMBER(5) default 0 not null
);

--生产管理，生产缺陷记录信息
create table TB_MP_DEFECTIVE_RECORD (
   ID                   NUMBER(10) PRIMARY KEY not null,
   PRODUCTION_RECORD_ID	NUMBER(10),
   DEFECTIVE_PROJECT  	VARCHAR2(256),
   DEFECTIVE_NUMBER		NUMBER(10),
   CREATE_USER          NUMBER(10),
   UPDATE_USER          NUMBER(10),
   CREATE_TIME          TIMESTAMP,
   UPDATE_TIME          TIMESTAMP,
   MARK_FOR_DELETE 		CHAR(1) default '0' not null,
   OPT_COUNTER     		NUMBER(5) default 0 not null
);




ALTER TABLE TM_DEVICE_MAINTENANCE ADD CURRENT_VALUE NUMBER(10) NULL;
COMMENT ON COLUMN TM_DEVICE_MAINTENANCE.CURRENT_VALUE IS '当前值(由TMP_MAINTENANCE_INFO_TEMP的触发器维护)';
ALTER TABLE TM_DEVICE_MAINTENANCE ADD LAST_COLLECT_TIIME TIMESTAMP(6) NULL;
COMMENT ON COLUMN TM_DEVICE_MAINTENANCE.LAST_COLLECT_TIIME IS '最新采集时间';



CREATE TABLE TMP_DEVICE_STATUS_TEMP
(
  DEVICE_NO         VARCHAR2(11),
  DEVICE_STATUS     VARCHAR2(16),
  DEVICE_FAULT_CODE VARCHAR2(32)
);
COMMENT ON TABLE TMP_DEVICE_STATUS_TEMP IS '钣金设备状态采集';
COMMENT ON COLUMN TMP_DEVICE_STATUS_TEMP.DEVICE_NO IS '设备号';
COMMENT ON COLUMN TMP_DEVICE_STATUS_TEMP.DEVICE_STATUS IS '设备状态';
COMMENT ON COLUMN TMP_DEVICE_STATUS_TEMP.DEVICE_FAULT_CODE IS '错误码';

-- 设备状态业务表
CREATE TABLE TMP_EQUIPMENT_STATUS
(
  ID                  NUMBER(10) NOT NULL
    PRIMARY KEY,
  TM_WORK_TIME_ID     NUMBER(10),
  TM_LINE_ID          NUMBER(10),
  TM_EQUIPMENT_ID     NUMBER(10),
  RUNNING_STATE       VARCHAR2(16),
  STATUS_NUMBER       VARCHAR2(32),
  STATUS_CONTENT      VARCHAR2(50),
  BEGIN_TIME          VARCHAR2(10),
  FINISH_TIME         VARCHAR2(10),
  DURATION            VARCHAR2(10),
  CREATE_TIME         DATE,
  UPDATE_USER         NUMBER(10),
  UPDATE_TIME         DATE,
  OPT_COUNTER         NUMBER(5),
  CREATE_USER         NUMBER(10),
  TM_CLASS_MANAGER_ID NUMBER(10)
);

COMMENT ON TABLE TMP_EQUIPMENT_STATUS IS '钣金设备状态';
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.TM_WORK_TIME_ID IS '工作日历ID';
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.TM_LINE_ID IS '产线ID';
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.TM_EQUIPMENT_ID IS '设备ID';
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.RUNNING_STATE IS '运行状态';
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.STATUS_NUMBER IS '状态编号';
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.STATUS_CONTENT IS '状态内容';
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.BEGIN_TIME IS '开始时间';
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.FINISH_TIME IS '结束时间';
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.DURATION IS '时长(min/s)';
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.TM_CLASS_MANAGER_ID IS '班组';

--钣金设备保养信息临时表
create table TMP_MAINTENANCE_INFO_TEMP (
   	MATERIAL_CODE    	VARCHAR2(64),
   	STATUS_1 			NUMBER(10),
   	STATUS_2 			NUMBER(10),
   	STATUS_3 			NUMBER(10)
);

--钣金生产信息临时表
CREATE TABLE TMP_PRODUCTION_TEMP
(
  BATCH_NUMBER          VARCHAR2(32),
  FINISH_NUMBER			NUMBER(10),
  PRODUCTION_TIME		NUMBER(10),
  STATUS				NUMBER(2),
  VELOCITY           	VARCHAR2(32),
  CYCLE_TIME           	VARCHAR2(32),
  STOP_ANGLE           	VARCHAR2(32)
);
COMMENT ON TABLE TMP_PRODUCTION_TEMP IS '钣金生产信息临时表';
COMMENT ON COLUMN TMP_PRODUCTION_TEMP.BATCH_NUMBER IS '批次号';
COMMENT ON COLUMN TMP_PRODUCTION_TEMP.FINISH_NUMBER IS '完成数';
COMMENT ON COLUMN TMP_PRODUCTION_TEMP.PRODUCTION_TIME IS '当前已生产时间';
COMMENT ON COLUMN TMP_PRODUCTION_TEMP.STATUS IS '0空闲1已发送2已接受3磨具校验完成4生产中5生产完成';
COMMENT ON COLUMN TMP_PRODUCTION_TEMP.VELOCITY IS '冲速';
COMMENT ON COLUMN TMP_PRODUCTION_TEMP.CYCLE_TIME IS '循环间隔时间';
COMMENT ON COLUMN TMP_PRODUCTION_TEMP.STOP_ANGLE IS '停止角度';
