INSERT INTO `ts_job`(JOB_NAME, JOB_TYPE, CRON_EXPRESSION, JOB_CLASS, JOB_METHOD, JOB_OBJECT) VALUES ('测试', '测试', '0 0/5 * * * ?', 'com.wis.basis.job.system.TestJob', 'test', 'testJob');

INSERT INTO TS_USER (ID, ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES (2,  'test', '2f604010b0ac5764e59edbf08b4fc68a', 'NORMAL',0,'测试用户','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (2, 1);

INSERT INTO TS_USER (ID, ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES (3,  'deptLeader', '53453b02a43be0b161cd0f9a5b546c2b', 'NORMAL',0,'部门领导','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (3, 1);

INSERT INTO TS_USER (ID, ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES (4,  'hr', 'f81ca59cd2fd5f2f38f1ce254091a1b7', 'NORMAL',0,'行政人员','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (4, 1);

INSERT INTO TS_USER (ID, ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES (5,  'finance', 'b157a4ca6332223959921da571bcae39', 'NORMAL',0,'财务人员','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (5, 1);

DROP TABLE IF EXISTS `tb_leave`;
CREATE TABLE `tb_leave` (
  ID bigint(10) NOT NULL AUTO_INCREMENT,
  PROCESS_INSTANCE_ID varchar(64) DEFAULT NULL,
  LEAVE_DATE_FROM datetime DEFAULT NULL,
  LEAVE_DATE_TO datetime DEFAULT NULL,
  LEAVE_REASON varchar(512) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `tb_business_trip`;
CREATE TABLE `tb_business_trip` (
  ID bigint(10) NOT NULL AUTO_INCREMENT,
  PROCESS_INSTANCE_ID varchar(64) DEFAULT NULL,
  DATE_FROM datetime DEFAULT NULL,
  DATE_TO datetime DEFAULT NULL,
  APPLY_AMOUNT varchar(64) DEFAULT NULL,
  TRIP_REASON varchar(512) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;