--权限数据
--钣金原材料表单权限
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802101, 8021, 'MetalplateView', '钣金原材料查看', '1', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802102, 8021, 'MetalplateAdd', '钣金原材料新增', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802103, 8021, 'MetalplateDelete', '钣金原材料删除', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802104, 8021, 'MetalplateUpdate', '钣金原材料修改', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802105, 8021, 'MetalplateImport', '钣金原材料导入', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802106, 8021, 'MetalplateExport', '钣金原材料导出', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802107, 8021, 'MetalplateModelMaintenance', '钣金原材料模具维护', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802108, 8021, 'MetalplateInventorySet', '库存设置', '0', 0);

--钣金原材料字段权限
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'MODEL_TYPE', '机种大类', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'PLACE_TYPE', '室内机/室外机', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'MATERIAL_DRAWING_NO', '材料图号', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'ASSEMBLY_LINE', '流水线用', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'ML_LEVEL', '图号等级', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'COATING_WITH', '涂装用', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'CW_LEVEL', '图号等级', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'MACHINING_SURFACE', '加工図面', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'MS_LEVEL', '图号等级', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'PROGRAM_NUMBER', '程序号', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'PROGRESSION', '累进', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'COMPONENT', '部品名', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'AFTER_PROCESS', '后工程', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'TEXTURE', '材质', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'PLATE_THICKNESS', '板厚', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'MATERIAL_SIZE', '开料尺寸', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'BATCH_NUMBER', '批次数', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'BATCH_CAP', '批次上限', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'STEP_NUMBER', '工程数', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'MACHINE_TAGS', '机台', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'MANUFACTURERS', '模具厂家', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'IDENTIFICATION_CODE', '完成识别码', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'TOOL_NUMBER', '模具编号', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'RES_TOOL_NUMBER', '备用模具', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'REMARK', '备注', 'SHEET_METAL_MATERIAL');

--钣金设备保养权限
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802201, 8022, 'MaintenanceView', '钣金设备保养查看', '1', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802202, 8022, 'MaintenanceAdd', '钣金设备保养新增', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802203, 8022, 'MaintenanceDelete', '钣金设备保养删除', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802204, 8022, 'MaintenanceUpdate', '钣金设备保养修改', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802205, 8022, 'MaintenanceImport', '钣金设备保养导入', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (802206, 8022, 'MaintenanceExport', '钣金设备保养导出', '0', 0);


insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8022, 'DEVICE_CODE', '设备编号', 'DEVICE_MAINTENANCE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8022, 'DEVICE_NAME', '设备名称', 'DEVICE_MAINTENANCE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8022, 'MAINTENANCE_PROJECT', '保养项目', 'DEVICE_MAINTENANCE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8022, 'MAINTENANCE_UNIT', '保养单位', 'DEVICE_MAINTENANCE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8022, 'MAINTENANCE_VALUE', '保养值', 'DEVICE_MAINTENANCE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8022, 'REMARK', '保养点检内容', 'DEVICE_MAINTENANCE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8022, 'MAINTENANCE_REMARK', '备注', 'DEVICE_MAINTENANCE');


--钣金线生产排产权限
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840401, 8404, 'ProductionScheduleView', '查看', '1', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840402, 8404, 'ProductionScheduleAdd', '新增', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840403, 8404, 'ProductionScheduleDelete', '删除', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840404, 8404, 'ProductionScheduleUpdate', '修改', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840405, 8404, 'ProductionScheduleInventory', '库存设置', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840406, 8404, 'ProductionScheduleSingle', '单次派工', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840407, 8404, 'ProductionScheduleBatch', '批量派工', '0', 0);

insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840408, 8404, 'ProductionScheduleCancel', '取消派工', '0', 0);

insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'TASKDATE', '日期', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'DATATYPE', '数据源', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'WORKSCHEDULE', '班次', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'MODEL', '型号', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'APCTOTALNUMBER', 'APC汇总数量', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'PLANNEDPRODUCTION', '计划数量', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'INVENTORYNUMBER', '剩余库存数量', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'SENDPERIODTIME', '派工时段', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_SCHEDULDATE', '日期', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_WORKSCHEDULE', '班次', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_MODEL', '型号', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_BATCHNUMBER', '批次', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_PRESS', '压机', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_MOULDS', '模具', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_DISPATCHNUMBER', '派工数', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_FINISHNUMBER', '成品数', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_SENDWORKERS', '派工人员', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_STATUS', '状态 ', 'PRODUCTION_SCHEDULE');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_DISPATCHTIME', '派工时间', 'PRODUCTION_SCHEDULE');

insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8021, 'REGIONMARK', '区域标识', 'SHEET_METAL_MATERIAL');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8404, 'S_REGIONMARK', '区域标识', 'PRODUCTION_SCHEDULE');

--钣金线生产记录权限
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840501, 8405, 'ProductionRecordView', '查看', '1', 0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840502, 8405, 'ProductionRecordDYSVIEW', '不良查看', '0', 0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840503, 8405, 'ProductionRecordDYSADD', '不良录入', '0', 0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840504, 8405, 'ProductionRecordDYS_UPDATE', '不良编辑', '0', 0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (840505, 8405, 'ProductionRecordDYS_CONFIRM', '不良确认', '0', 0);

insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'PRODUCTIONDATE', '生产日期', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'MODEL', '型号', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'BATCHNUMBER', '批次', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'WORKPEOPLE', '作业者', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'WORKSCHEDULE', '班次', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'PRESS', '压机', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'MOULDS', '模具', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'PLANNEDCYCLES', '计划生产回数', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'PRACTICALCYCLES', '实际生产回数', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'DEFECTIVENUMBER', '不良品数', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'INVENTORYCONSUMPTION', '库存消耗', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'PRODUCTIONTIME', '生产时间', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'PERIODTAKETIME', '段取时间', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'PLACETIME', '放置时间', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'ALARMNUMBER', '报警回数', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'STARTTIME', '作业开始时间', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'ENDTIME', '作业结束时间', 'PRODUCTION_RECORD');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8405, 'REGIONMARK', '区域标识', 'PRODUCTION_RECORD');

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL, 'MENU_MAINTENANCE_REPORT','保养管理表','Maintenance report',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (8721, 87, 'MENU_MAINTENANCE_REPORT', 'bar-chart', '/maintenance_report/listInput.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (872101, 8721, 'menu_maintenance_report', '保养管理表',1);

INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL, 'MENU_MAINTENANCE_WARN_REPORT','设备报警报表','Maintenance warn report',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (8722, 87, 'MENU_MAINTENANCE_WARN_REPORT', 'bar-chart', '/maintenance_report/warn_report.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (872202, 8722, 'menu_maintenance_report', '设备报警报表',1);



INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL, 'MENU_PMC_REPORT','PMC报表','PMC report',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (8723, 87, 'MENU_PMC_REPORT', 'bar-chart', '/maintenance_report/pmc_report.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (872301, 8723, 'menu_pmc_report', 'PMC报表',1);


INSERT INTO TS_LANGUAGE(ID,CODE,ZH_CN,EN_US,OPT_COUNTER) VALUES (SEQ_LANGUAGE_ID.NEXTVAL, 'MENU_TB_NO_FAULT_DETAILS','钣金-非故障明细','TB no fault details',0);
INSERT INTO TS_MENU (ID, PARENT_ID, MENU_NAME, ICON_CLS, PAGE_URL ) VALUES (8724, 87, 'MENU_TB_NO_FAULT_DETAILS', 'bar-chart', '/tb_no_fault_details/listInput.do' );
INSERT INTO TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME,IS_MENU_PERMISSION) VALUES (872401, 8724, 'menu_tb_no_fault_details', '钣金-非故障明细',1);



--钣金设备实时状态
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (850501, 8505, 'mpEquipmentRtView', '钣金设备实时状态查看', '1', 0);

--钣金设备历史信息
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (850601, 8506, 'mpEquipmentHsView', '钣金设备历史信息查看', '1', 0);
insert into TS_PERMISSION (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, IS_MENU_PERMISSION, OPT_COUNTER)
values (850602, 8506, 'mpEquipmentHsExport', '钣金设备历史信息导出', '0', 0);

insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8505, 'TMWORKTIME', '工作时间', 'MPEQUIPMENTRT');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8505, 'TMLINE', '产线', 'MPEQUIPMENTRT');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8505, 'TMEQUIPMENT', '设备', 'MPEQUIPMENTRT');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8505, 'RUNNINGSTATE', '运行状态', 'MPEQUIPMENTRT');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8505, 'STATUSNUMBER', '状态编号', 'MPEQUIPMENTRT');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8505, 'STATUSCONTENT', '状态内容', 'MPEQUIPMENTRT');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8505, 'BEGINTIME', '开始时间', 'MPEQUIPMENTRT');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8505, 'FINISHTIME', '结束时间', 'MPEQUIPMENTRT');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8505, 'DURATION', '时长(min/s)', 'MPEQUIPMENTRT');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8505, 'TMCLASSMANAGER', '班组', 'MPEQUIPMENTRT');

insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8506, 'TMWORKTIME', '工作时间', 'MPEQUIPMENTHS');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8506, 'TMLINE', '产线', 'MPEQUIPMENTHS');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8506, 'TMEQUIPMENT', '设备', 'MPEQUIPMENTHS');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8506, 'RUNNINGSTATE', '运行状态', 'MPEQUIPMENTHS');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8506, 'STATUSNUMBER', '状态编号', 'MPEQUIPMENTHS');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8506, 'STATUSCONTENT', '状态内容', 'MPEQUIPMENTHS');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8506, 'BEGINTIME', '开始时间', 'MPEQUIPMENTHS');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8506, 'FINISHTIME', '结束时间', 'MPEQUIPMENTHS');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8506, 'DURATION', '时长(min/s)', 'MPEQUIPMENTHS');
insert into TS_FORM_PERMISSION_NEW (ID, MENU_ID, PERMISSION_CODE, PERMISSION_NAME, MODULE) values (SEQ_FORM_PERMISSION_NEW_ID.NEXTVAL, 8506, 'TMCLASSMANAGER', '班组', 'MPEQUIPMENTHS');

--钣金设备生产管理报表
INSERT INTO TS_PERMISSION  VALUES('872502','8726','ProductMrgView','生产报表查看',1,0);






commit;