--增加区域标识
ALTER TABLE TM_SHEET_METAL_MATERIAL ADD REGION_MARK VARCHAR2(32);
ALTER TABLE TB_MP_SCHEDUL ADD REGION_MARK VARCHAR2(32);
ALTER TABLE TB_MP_PRODUCTION_RECORD ADD REGION_MARK VARCHAR2(32);
ALTER TABLE TB_MP_SCHEDUL ADD CONSUME_APC_TOTAL VARCHAR2(32);
ALTER TABLE TB_MP_SCHEDUL MODIFY BATCH_NUMBER VARCHAR2(32);
ALTER TABLE TB_MP_SOURCE_DATA ADD STATUS NUMBER(1) DEFAULT 0;
ALTER TABLE TB_MP_SCHEDUL MODIFY STATUS NUMBER(2);
ALTER TABLE TB_MP_SCHEDUL MODIFY DISPATCH_TIME TIMESTAMP(6);
ALTER TABLE TB_MP_SCHEDUL MODIFY CONSUME_APC_TOTAL NUMBER(10);

ALTER TABLE TB_MP_SCHEDUL ADD RELATION_ID NUMBER(10);
ALTER TABLE TB_MP_SCHEDUL ADD SORT VARCHAR2(32);
COMMENT ON COLUMN TB_MP_SCHEDUL.RELATION_ID  IS '关联ID';
COMMENT ON COLUMN TB_MP_SCHEDUL.SORT  IS '排序';
ALTER TABLE TB_MP_SCHEDUL ADD SYN_POSITION VARCHAR2(16);
COMMENT ON COLUMN TB_MP_SCHEDUL.SYN_POSITION IS '生产顺位';

ALTER TABLE TB_MP_PRODUCTION_RECORD MODIFY BATCH_NUMBER VARCHAR2(32);
ALTER TABLE TB_MP_PRODUCTION_RECORD ADD STATUS VARCHAR2(2);

ALTER TABLE TB_MP_SCHEDUL ADD VERIFY VARCHAR2(150);
COMMENT ON COLUMN TB_MP_SCHEDUL.VERIFY  IS '模具校验状态';

ALTER TABLE TM_DEVICE_MAINTENANCE ADD MAINTENANCE_CODE VARCHAR2(64);
COMMENT ON COLUMN TM_DEVICE_MAINTENANCE.MAINTENANCE_CODE IS '保养项目编码';

ALTER TABLE TB_MP_PRODUCTION_RECORD ADD VELOCITY VARCHAR2(32);
ALTER TABLE TB_MP_PRODUCTION_RECORD ADD CYCLE_TIME VARCHAR2(32);
ALTER TABLE TB_MP_PRODUCTION_RECORD ADD STOP_ANGLE VARCHAR2(32);
COMMENT ON COLUMN TB_MP_PRODUCTION_RECORD.VELOCITY IS '冲速';
COMMENT ON COLUMN TB_MP_PRODUCTION_RECORD.CYCLE_TIME IS '循环间隔时间';
COMMENT ON COLUMN TB_MP_PRODUCTION_RECORD.STOP_ANGLE IS '停止角度';

ALTER TABLE TB_MP_SCHEDUL ADD WORK_TIME_ID NUMBER(10);
COMMENT ON COLUMN TB_MP_SCHEDUL.WORK_TIME_ID  IS '工作时间ID';

ALTER TABLE TM_SHEET_METAL_MATERIAL ADD INVENTORY_NUMBER NUMBER(10) DEFAULT 0;
COMMENT ON COLUMN TM_SHEET_METAL_MATERIAL.INVENTORY_NUMBER  IS '剩余库存数';

ALTER TABLE TB_MP_SOURCE_DATA ADD MATERIAL_ID NUMBER(10);
COMMENT ON COLUMN TB_MP_SOURCE_DATA.MATERIAL_ID  IS '关联原材料主数据';

ALTER TABLE TM_SHEET_METAL_MATERIAL ADD STANDARD_CT NUMBER(10,2) DEFAULT 0;
COMMENT ON COLUMN TM_SHEET_METAL_MATERIAL.STANDARD_CT  IS '标准CT';

alter table TM_DEVICE_MAINTENANCE add status number(1) default 0;
comment on column TM_DEVICE_MAINTENANCE.status  is '状态 0关闭 1打开';

ALTER TABLE TB_MP_SCHEDUL ADD ISSUED_TIME TIMESTAMP(6);
ALTER TABLE TB_MP_SCHEDUL ADD START_TIME TIMESTAMP(6);
COMMENT ON COLUMN TB_MP_SCHEDUL.ISSUED_TIME  IS '任务下发PLC时间';
COMMENT ON COLUMN TB_MP_SCHEDUL.START_TIME  IS '任务开始生产时间';

ALTER TABLE TB_MP_SCHEDUL ADD PRODUCTION_TIME NUMBER(10);
COMMENT ON COLUMN TB_MP_SCHEDUL.PRODUCTION_TIME  IS '实际生产耗时';

ALTER TABLE TB_MP_SCHEDUL ADD VERIFY_DURATION NUMBER(10) DEFAULT 0;
COMMENT ON COLUMN TB_MP_SCHEDUL.VERIFY_DURATION IS '换模时间';

ALTER TABLE TM_SHEET_METAL_MATERIAL ADD PLC_NO VARCHAR2(16);
COMMENT ON COLUMN TM_SHEET_METAL_MATERIAL.PLC_NO  IS 'PLC该程序号对应的编码';

ALTER TABLE TB_MP_SCHEDUL ADD MATERIAL_ID NUMBER(10);
COMMENT ON COLUMN TB_MP_SCHEDUL.MATERIAL_ID  IS '根据所选的图号关联主数据';

ALTER TABLE TMP_EQUIPMENT_STATUS ADD IS_REST VARCHAR2(1);
COMMENT ON COLUMN TMP_EQUIPMENT_STATUS.IS_REST  IS '是否休息';

