INSERT INTO ts_job(JOB_NAME, JOB_TYPE, CRON_EXPRESSION, JOB_CLASS, JOB_METHOD, JOB_OBJECT) VALUES ('测试', '测试', '0 0/5 * * * ?', 'com.wis.basis.job.system.TestJob', 'test', 'testJob');

INSERT INTO TS_USER (ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES ('test', '2f604010b0ac5764e59edbf08b4fc68a', 'NORMAL',0,'测试用户','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (2, 1);

INSERT INTO TS_USER (ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES ('deptLeader', '53453b02a43be0b161cd0f9a5b546c2b', 'NORMAL',0,'部门领导','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (3, 1);

INSERT INTO TS_USER (ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES ('hr', 'f81ca59cd2fd5f2f38f1ce254091a1b7', 'NORMAL',0,'行政人员','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (4, 1);

INSERT INTO TS_USER (ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES ('finance', 'b157a4ca6332223959921da571bcae39', 'NORMAL',0,'财务人员','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (5, 1);

if object_id('dbo.tb_leave') is not null
begin
  drop table dbo.tb_leave
end;
CREATE TABLE tb_leave (
  ID BIGINT NOT NULL IDENTITY(1,1),
  PROCESS_INSTANCE_ID varchar(64) DEFAULT NULL,
  LEAVE_DATE_FROM datetime DEFAULT NULL,
  LEAVE_DATE_TO datetime DEFAULT NULL,
  LEAVE_REASON varchar(512) DEFAULT NULL,
  PRIMARY KEY (ID)
);

if object_id('dbo.tb_business_trip') is not null
begin
  drop table dbo.tb_business_trip
end;
CREATE TABLE tb_business_trip (
  ID BIGINT NOT NULL IDENTITY(1,1),
  PROCESS_INSTANCE_ID varchar(64) DEFAULT NULL,
  DATE_FROM datetime DEFAULT NULL,
  DATE_TO datetime DEFAULT NULL,
  APPLY_AMOUNT varchar(64) DEFAULT NULL,
  TRIP_REASON varchar(512) DEFAULT NULL,
  PRIMARY KEY (ID)
) ;