INSERT INTO ts_job(ID,JOB_NAME, JOB_TYPE, CRON_EXPRESSION, JOB_CLASS, JOB_METHOD, JOB_OBJECT) VALUES (SEQ_JOB_ID.NEXTVAL,'测试', '测试', '0 0/5 * * * ?', 'com.wis.basis.job.system.TestJob', 'test', 'testJob');

INSERT INTO TS_USER (ID, ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES (2,  'test', '2f604010b0ac5764e59edbf08b4fc68a', 'NORMAL',0,'测试用户','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (2, 1);

INSERT INTO TS_USER (ID, ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES (3,  'deptLeader', '53453b02a43be0b161cd0f9a5b546c2b', 'NORMAL',0,'部门领导','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (3, 1);

INSERT INTO TS_USER (ID, ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES (4,  'hr', 'f81ca59cd2fd5f2f38f1ce254091a1b7', 'NORMAL',0,'行政人员','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (4, 1);

INSERT INTO TS_USER (ID, ACCOUNT, PASSWORD, STATUS, MARK_FOR_DELETE,USER_NAME,EMAIL,GENDER,PHONE) VALUES (5,  'finance', 'b157a4ca6332223959921da571bcae39', 'NORMAL',0,'财务人员','qizhang@163.com','M','15890987231');
INSERT INTO TR_ROLE_USER (USER_ID, ROLE_ID) VALUES (5, 1);

drop table tb_leave cascade constraints;
DROP sequence SEQ_LEAVE_ID;
CREATE TABLE tb_leave (
  ID NUMBER(10) PRIMARY KEY NOT NULL,
  PROCESS_INSTANCE_ID varchar2(64) DEFAULT NULL,
  LEAVE_DATE_FROM TIMESTAMP,
  LEAVE_DATE_TO TIMESTAMP,
  LEAVE_REASON Nvarchar2(512) DEFAULT NULL
);
create sequence SEQ_LEAVE_ID
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
cache 20;

drop table tb_business_trip cascade constraints;
DROP sequence SEQ_TRIP_ID;
CREATE TABLE tb_business_trip (
  ID NUMBER(10) PRIMARY KEY NOT NULL,
  PROCESS_INSTANCE_ID varchar2(64) DEFAULT NULL,
  DATE_FROM TIMESTAMP,
  DATE_TO TIMESTAMP,
  APPLY_AMOUNT varchar2(64),
  TRIP_REASON varchar2(512)
);
create sequence SEQ_TRIP_ID
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
cache 20;